version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "jekyll"
        versions: ["<4.0.0"]
